### ISSUE TITLE
Missing bibliographic references

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_bugs_import#12]
The import system reports a number of unknown bibliographic references

```SQL
with bugs_values as (
    select string_to_array(translate(bugs_data, '{}', ''), ',') as data
    from bugs_import.bugs_errors
    where TRUE
      and message = 'No reference found'
) select distinct data[5]
  from bugs_values
```
Result:
```
Johnson 2003a	1
Böhme 2005	855
Böcher 1988	4
Hoskovec & Rejzek 1997	1
Aalto et al. (1984)	1
```

**Comment by roger-mahler** [comment]
A search in the bibliographic reference table gives potential candidate matches:
```
Johnson 2003a                        (tbl_biblio.bugs_reference 'Johnson 2003' exists, lots of other Johnsons)
Böhme 2005                            (tbl_biblio.bugs_reference 'Bohme 2005' exists)
Böcher 1988'                           (tbl_biblio.bugs_reference 'Bocher 1988' exists)
Hoskovec & Rejzek 1997'        Hoskovec M., Rejzek M. (1997-2012) West Palaearctic Cerambycidae????
Aalto et al. (1984)                    (tbl_biblio.bugs_reference 'Aalto et al (1984)' exists)
```

**Comment by visead** [comment]
These are correct mappings:
Böhme 2005: (tbl_biblio.bugs_reference 'Bohme 2005' exists)
Böcher 1988: (tbl_biblio.bugs_reference 'Bocher 1988' exists)
Aalto et al. (1984): (tbl_biblio.bugs_reference 'Aalto et al (1984)' exists)

**Comment by visead** [comment]
Need to know which Bugs table is providing the unmapped references. Not found in TBiblio.

**Comment by roger-mahler** [comment]
Specify where from which table the affected Bugs-data is from.

**Comment by roger-mahler** [comment]
2986	TSynonym	{47.0040034,Simplocaria,frigida,Krog.,Böcher 1988,null}		No reference found	2019-05-07 14:13:51.697156+02	{47.0040034,Simplocaria,frigida,Krog.,Böcher 1988,null}
2987	TSynonym	{47.0040034,Simplocaria,remota,Brown,Böcher 1988,null}		No reference found	2019-05-07 14:13:51.773048+02	{47.0040034,Simplocaria,remota,Brown,Böcher 1988,null}
2984	TSynonym	{23.1601021,Atheta,hyperborea,Brundin,Böcher 1988,null}		No reference found	2019-05-07 14:12:23.504689+02	{23.1601021,Atheta,hyperborea,Brundin,Böcher 1988,null}
2985	TSynonym	{23.1881365,Atheta,fungi,of other Greenland auctt.,Böcher 1988,null}		No reference found	2019-05-07 14:12:47.761103+02	{23.1881365,Atheta,fungi,of other Greenland auctt.,Böcher 1988,null}
2988	TSynonym	{21.019003,Acrotrichis,chevrolati,auctt. Misspelling,Johnson 2003a,null}		No reference found	2019-05-07 14:18:27.520409+02	{21.019003,Acrotrichis,chevrolati,auctt. Misspelling,Johnson 2003a,null}
2990	TSynonym	{23.1040675,Quedius,boops,of Greenland list,Böcher 1988,null}		No reference found	2019-05-07 14:26:24.572729+02	{23.1040675,Quedius,boops,of Greenland list,Böcher 1988,null}
2996	TSynonym	{83.040001,Cylindronotus,null,auctt partim (misspelling),Aalto et al. (1984),null}		No reference found	2019-05-07 14:32:49.994493+02	{83.040001,Cylindronotus,null,auctt partim (misspelling),Aalto et al. (1984),null}

**Comment by roger-mahler** [comment]
@visead bump

**Comment by visead** [comment]
Corrected in 2020-01-07 Bugsdata file.
