### ISSUE TITLE
Unknown association types

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_bugs_import#13]
Bugs import reports a number of missing association types. Some of them have a match to existing types in which case a translation needs to be added to the import system, while other association types must be added to SEAD.

Bugs value | Candidate SEAD match
-- | --
has undefined association with | undefined association with
in same streams as |  
inquiline with | inquiline
in same ponds as |  
found around nests of | around nests of
is found with |  
is predated in nests by | is predated in own nests by
in similar woodland pools as |  
swarms with |  
in same upland habitat |  
is predated on by | is predated by
in same log as | in same wood as
larvae predated on by | larvae predated by
is cuckoo parasite in burrows of |  
kleptoparasite in nest of | is kleptoparasitic in nests of
pupae parasitized by? | pupae is parasitized by
is semi-parasitic with |  
parasitizes pupae of? | pupae is parasitized by
inquiline with? | inquiline
is parasite of |  
in smae habitat | in same habitat
on burnt ground with | on burnt ground
pupa parasitised by | pupae parasitised by
endoparasite of pupa |

**Comment by visead** [comment]
Check database "sead_bugs_import_20180503" for missing association types (contains 98 types, compared to sead_master_8 and others.

**Comment by roger-mahler** [comment]
Same number of records (92) in sead_staging_bugs and old import from 2017 and 2018.

**Comment by roger-mahler** [comment]
in same streams as	10
kleptoparasite in nest of	1
larvae predated on by	1
is predated on by	2
in similar woodland pools as	2
is predated in nests by	3
is semi-parasitic with	1
pupae parasitized by?	1
inquiline with	8
inquiline with?	1
on burnt ground with	1
swarms with	2
is parasite of	1
in same log as	1
parasitizes pupae of?	1
in same ponds as	6
found around nests of	5
has undefined association with	473
is found with	4
in same upland habitat	2
is cuckoo parasite in burrows of	1

**Comment by roger-mahler** [comment]
Resolved by [20191012_DML_ASSOCIATION_TYPE_UPDATES #15](https://github.com/humlab-sead/sead_change_control/issues/15)
