### ISSUE TITLE
Bugs ecocode GeoJSON export returns wrong values (counts and sums).

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_bugs_import#19]
This issue is related to #17 and #18. These two queries should return the same data:
```sql
SELECT ps.physical_sample_id,
            sum(ab.abundance) AS abundance_sum,
            count(ab.abundance) AS abundance_count
FROM tbl_analysis_entities ae
JOIN tbl_datasets ds
  ON ds.dataset_id = ae.dataset_id
JOIN tbl_dataset_masters ms
  ON ms.master_set_id = ds.master_set_id     
JOIN tbl_physical_samples ps ON ps.physical_sample_id = ae.physical_sample_id
JOIN tbl_abundances ab ON ab.analysis_entity_id = ae.analysis_entity_id
JOIN tbl_taxa_tree_master tm ON tm.taxon_id = ab.taxon_id
WHERE ms.master_name = 'Bugs database'
GROUP BY ps.physical_sample_id
ORDER BY 1;
```
```sql

SELECT  ps.physical_sample_id, 
        sum(ab.abundance) AS abundance_sum,
        count(ab.abundance) AS abundance_count
FROM tbl_analysis_entities ae
JOIN tbl_datasets ds
  ON ds.dataset_id = ae.dataset_id
JOIN tbl_dataset_masters ms
  ON ms.master_set_id = ds.master_set_id
JOIN tbl_physical_samples ps
  ON ps.physical_sample_id = ae.physical_sample_id
JOIN tbl_abundances ab
  ON ab.analysis_entity_id = ae.analysis_entity_id
--JOIN tbl_taxa_tree_master tm
--  ON tm.taxon_id = ab.taxon_id
JOIN tbl_ecocodes e
  ON ab.taxon_id = e.taxon_id
JOIN tbl_ecocode_definitions ed
  ON e.ecocode_definition_id = ed.ecocode_definition_id
JOIN tbl_ecocode_groups eg
  ON eg.ecocode_group_id = ed.ecocode_group_id
WHERE TRUE
  AND eg.ecocode_system_id = 2
  AND ms.master_name = 'Bugs database'
GROUP BY ps.physical_sample_id
ORDER BY 1;
```

**Comment by roger-mahler** [comment]
Also note that GeoJSON export in production (materialized view `physical_sample_ecocode_abundance` lacks filter on master data set and ecocode system id. This will not work in databases that contain other non-Bugs data.

**Comment by Loer0022** [comment]
I believe this is an issue of misunderstanding the Bugs data, because the two queries are requesting different things and cannot provide the same output because of that.

What the first query is returning is taxa in relation to physical samples, meaning that only a value of 1 can be returned because there can only be one taxa (species) and that means for e.g. sample 2275 that there will be 125 different species. However, if we look at the second query it is returning taxa as well as the habitats they are representing meaning that for each taxa there can be a value of 1+X in abundance, where each species can represent one or more habitats. The abundance is therefore often greater than the total number of species present in the sample.

The two shouldn’t return the same data and they are exporting correct values.

-----

The first of the images below is the origional output from the first query showing that there are 125 species in sample 2275, the second image is only showing the individual taxa instead of the total count/sum output.

![Querry 1](https://user-images.githubusercontent.com/55080011/65431123-3ff3c600-de19-11e9-8840-1d09ef1cd547.PNG)

![Query 1 - true export](https://user-images.githubusercontent.com/55080011/65431073-2c485f80-de19-11e9-979b-d2ec18cebb84.PNG)

-----

If we look at the second query output we can see that the Count and Sum are taking onto consideraiton the species habitat, and these values are correct when comparing with previously exported data. We can further see that each taxa has a abundance in general above 1 because of the habitats they are representing, and further dividing it to see each taxa in relation to ecocode_definitions they are representing (which the first query does not have) we can further control that the output is correct.

![Query 2 - true export2](https://user-images.githubusercontent.com/55080011/65431389-b1337900-de19-11e9-9196-847734bbfbbe.PNG)

![Query 2 - true export](https://user-images.githubusercontent.com/55080011/65431293-86e1bb80-de19-11e9-8e58-72823f3ae28e.PNG)

![Query 2](https://user-images.githubusercontent.com/55080011/65431325-9234e700-de19-11e9-8a15-94ea4a4b1855.png)

In the last image we can see that ecocodes_definitions_ID 10 is shown twice, because the row is not unique this will not cause any issue since it isn't counted twice.

**Comment by visead** [comment]
Bump @Loer0022 
Then run GeoJSON export and send new file to DataARC

**Comment by Loer0022** [comment]
-- FUNCTION: humlab_utility.fn_sample_ecocode_abundances(integer, integer, integer)

-- DROP FUNCTION humlab_utility.fn_sample_ecocode_abundances(integer, integer, integer);

CREATE OR REPLACE FUNCTION humlab_utility.fn_sample_ecocode_abundances(
	v_ecocode_system_id integer,
	v_ecocode_group_id integer,
	v_master_set_id integer)
    RETURNS TABLE(physical_sample_id integer, ecocode_name character varying, abundance_count integer, abundance_sum integer) 
    LANGUAGE 'plpgsql'

    COST 100
    VOLATILE 
    ROWS 1000
AS $BODY$
begin
    return query
    with ecocodes as (
        /* This is all unique ecocode names within selected system and group (used in cross join) */
        select ed.name as ecocode_name
        from tbl_ecocode_definitions ed
        join tbl_ecocode_groups eg using (ecocode_group_id)
        where eg.ecocode_system_id = v_ecocode_system_id
          and eg.ecocode_group_id = v_ecocode_group_id
        -- select unnest(v_ecocodes) as ecocode_name
    ), taxon_ecocodes as (
        /* This is just a taxon to eco-code mapping (for selected system and group) */
        select taxon_id, ed.name as ecocode_name
        from tbl_ecocode_groups eg
        join tbl_ecocode_definitions ed using (ecocode_group_id)
        join tbl_ecocodes e using (ecocode_definition_id)
        where eg.ecocode_system_id = v_ecocode_system_id
          and eg.ecocode_group_id = v_ecocode_group_id
    ), samples as (
        /* Only consider samples that belong to specified master dataset */
        select distinct samples.physical_sample_id
        from tbl_physical_samples samples
        join tbl_analysis_entities using (physical_sample_id)
        join tbl_datasets using (dataset_id)
        join tbl_dataset_masters using (master_set_id)
        where tbl_dataset_masters.master_set_id = v_master_set_id
          and tbl_dataset_masters.master_name =  'Bugs database'
    ), sample_ecocode_abundances as (
        /* Compute count and sum by sample and ecocode */
        select samples.physical_sample_id, taxon_ecocodes.ecocode_name, count(abundance_id) as abundance_count, sum(abundance) as abundance_sum
        from samples
        join tbl_analysis_entities using (physical_sample_id)
        join tbl_abundances using (analysis_entity_id)
        join taxon_ecocodes using (taxon_id)
        group by samples.physical_sample_id, taxon_ecocodes.ecocode_name

    ) select x.physical_sample_id,
             x.ecocode_name::character varying(150),
             coalesce(sample_ecocode_abundances.abundance_count, 0)::int,
             coalesce(sample_ecocode_abundances.abundance_sum, 0)::int
      from (
          select samples.physical_sample_id, ecocodes.ecocode_name
          from samples
          cross join ecocodes
      ) as x
      left join sample_ecocode_abundances using (physical_sample_id, ecocode_name);
end $BODY$;

ALTER FUNCTION humlab_utility.fn_sample_ecocode_abundances(integer, integer, integer)
    OWNER TO postgres;


-- FUNCTION: humlab_utility.fn_ecocode_crosstab_2_7(integer, text)

-- DROP FUNCTION humlab_utility.fn_ecocode_crosstab_2_7(integer, text);

CREATE OR REPLACE FUNCTION humlab_utility.fn_ecocode_crosstab_2_7(
	p_master_set_id integer,
	p_sum_or_count text)
    RETURNS TABLE(agg_type text, physical_sample_id integer, Aquatics integer, "Indicators: Standing water" integer, "Indicators: Running water" integer, "Pasture/Dung" integer, Meadowland integer, "Wood and trees" integer, "Indicators: Deciduous" integer, "Indicators: Coniferous" integer, "Wetlands/marshes" integer, "Open wet habitats" integer, "Disturbed/arable" integer, "Sandy/dry disturbed/arable" integer, "Dung/foul habitats" integer, Carrion integer, "Indicators: Dung" integer, "Mould beetles" integer, "General synanthropic" integer, "Stored grain pest" integer, "Dry dead wood" integer, "Heathland & moorland" integer, Halotolerant integer, Ectoparasite integer) 
    LANGUAGE 'plpgsql'

    COST 100
    VOLATILE 
    ROWS 1000
AS $BODY$
declare
  v_sql text;
  v_abundance_index int;
begin
    v_abundance_index = case when p_sum_or_count = 'count' then 1 else 2 end;
    return query
        select p_sum_or_count::text as agg_type, cx.physical_sample_id, cx."Aquatics" , cx."Indicators: Standing water" , cx."Indicators: Running water" , cx."Pasture/Dung" , cx."Meadowland" , cx."Wood and trees" , cx."Indicators: Deciduous" , cx."Indicators: Coniferous" , cx."Wetlands/marshes" , cx."Open wet habitats" , cx."Disturbed/arable" , cx."Sandy/dry disturbed/arable" , cx."Dung/foul habitats" , cx."Carrion", cx."Indicators: Dung", cx."Mould beetles", cx."General synanthropic", cx."Stored grain pest", cx."Dry dead wood", cx."Heathland & moorland", cx."Halotolerant", cx."Ectoparasite"
        from crosstab(format('
			select physical_sample_id, ecocode_name::text, (array[abundance_count, abundance_sum])[%s]::int as abundance
        	from humlab_utility.fn_sample_ecocode_abundances(2, 7, %s)', v_abundance_index, p_master_set_id), 
		'values (''Aquatics''::text), (''Indicators: Standing water''::text), (''Indicators: Running water''::text), (''Pasture/Dung''::text), (''Meadowland''::text), (''Wood and trees''::text), 
		(''Indicators: Deciduous''::text), (''Indicators: Coniferous''::text), (''Wetlands/marshes''::text), (''Open wet habitats''::text), (''Disturbed/arable''::text), (''Sandy/dry disturbed/arable''::text), 
		(''Dung/foul habitats''::text), (''Carrion''::text), (''Indicators: Dung''::text), (''Mould beetles''::text), (''General synanthropic''::text), (''Stored grain pest''::text), (''Dry dead wood''::text), 
		(''Heathland & moorland''::text), (''Halotolerant''::text), (''Ectoparasite''::text)') as cx (physical_sample_id int, "Aquatics" int, "Indicators: Standing water" int, "Indicators: Running water" int, 
		"Pasture/Dung" int, "Meadowland" int, "Wood and trees" int, "Indicators: Deciduous" int, "Indicators: Coniferous" int, "Wetlands/marshes" int, "Open wet habitats" int, "Disturbed/arable" int, 
		"Sandy/dry disturbed/arable" int, "Dung/foul habitats" int, "Carrion" int, "Indicators: Dung" int, "Mould beetles" int, "General synanthropic" int, "Stored grain pest" int, "Dry dead wood" int,
		"Heathland & moorland" int, "Halotolerant" int, "Ectoparasite" int)
    ;
end;
$BODY$;

ALTER FUNCTION humlab_utility.fn_ecocode_crosstab_2_7(integer, text)
    OWNER TO postgres;


-- View: humlab_utility.ecocode_dating

-- DROP VIEW humlab_utility.ecocode_dating;

CREATE OR REPLACE VIEW humlab_utility.ecocode_dating AS
 SELECT a.physical_sample_id,
    a.agg_type,
    a.Aquatics,
    a."Indicators: Standing water",
    a."Indicators: Running water",
    a."Pasture/Dung",
    a.Meadowland,
    a."Wood and trees",
    a."Indicators: Deciduous",
    a."Indicators: Coniferous",
    a."Wetlands/marshes",
    a."Open wet habitats",
    a."Disturbed/arable",
    a."Sandy/dry disturbed/arable",
    a."Dung/foul habitats",
    a.Carrion,
    a."Indicators: Dung",
    a."Mould beetles",
    a."General synanthropic",
    a."Stored grain pest",
    a."Dry dead wood",
    a."Heathland & moorland",
    a.Halotolerant,
    a.Ectoparasite,
    d.location_name,
    d.site_id,
    d.site_name,
    d.latitude_dd,
    d.longitude_dd,
    d.dating_type,
    d.age_older,
    d.age_younger,
    d.age_name,
    d.age_abbreviation,
    ps.sample_group_id,
    ps.alt_ref_type_id,
    ps.sample_type_id,
    ps.sample_name,
    ps.date_updated,
    ps.date_sampled
   FROM humlab_utility.fn_ecocode_crosstab_2_7(1, 'count'::text) a(agg_type, physical_sample_id, Aquatics, "Indicators: Standing water", "Indicators: Running water", "Pasture/Dung", Meadowland, "Wood and trees", "Indicators: Deciduous", "Indicators: Coniferous", "Wetlands/marshes", "Open wet habitats", "Disturbed/arable", "Sandy/dry disturbed/arable", "Dung/foul habitats", Carrion, "Indicators: Dung", "Mould beetles", "General synanthropic", "Stored grain pest", "Dry dead wood", "Heathland & moorland", Halotolerant, Ectoparasite)
     JOIN humlab_utility.physical_sample_dating d USING (physical_sample_id)
     JOIN tbl_physical_samples ps USING (physical_sample_id);

ALTER TABLE humlab_utility.ecocode_dating
    OWNER TO postgres;

**Comment by Loer0022** [comment]
```sql
-- FUNCTION: humlab_utility.fn_sample_ecocode_abundances(integer, integer, integer)

-- DROP FUNCTION humlab_utility.fn_sample_ecocode_abundances(integer, integer, integer);

CREATE OR REPLACE FUNCTION humlab_utility.fn_sample_ecocode_abundances(
	v_ecocode_system_id integer,
	v_ecocode_group_id integer,
	v_master_set_id integer)
    RETURNS TABLE(physical_sample_id integer, ecocode_name character varying, abundance_count integer, abundance_sum integer) 
    LANGUAGE 'plpgsql'

    COST 100
    VOLATILE 
    ROWS 1000
AS $BODY$
begin
    return query
    with ecocodes as (
        /* This is all unique ecocode names within selected system and group (used in cross join) */
        select ed.name as ecocode_name
        from tbl_ecocode_definitions ed
        join tbl_ecocode_groups eg using (ecocode_group_id)
        where eg.ecocode_system_id = v_ecocode_system_id
          and eg.ecocode_group_id = v_ecocode_group_id
        -- select unnest(v_ecocodes) as ecocode_name
    ), taxon_ecocodes as (
        /* This is just a taxon to eco-code mapping (for selected system and group) */
        select taxon_id, ed.name as ecocode_name
        from tbl_ecocode_groups eg
        join tbl_ecocode_definitions ed using (ecocode_group_id)
        join tbl_ecocodes e using (ecocode_definition_id)
        where eg.ecocode_system_id = v_ecocode_system_id
          and eg.ecocode_group_id = v_ecocode_group_id
    ), samples as (
        /* Only consider samples that belong to specified master dataset */
        select distinct samples.physical_sample_id
        from tbl_physical_samples samples
        join tbl_analysis_entities using (physical_sample_id)
        join tbl_datasets using (dataset_id)
        join tbl_dataset_masters using (master_set_id)
        where tbl_dataset_masters.master_set_id = v_master_set_id
          and tbl_dataset_masters.master_name =  'Bugs database'
    ), sample_ecocode_abundances as (
        /* Compute count and sum by sample and ecocode */
        select samples.physical_sample_id, taxon_ecocodes.ecocode_name, count(abundance_id) as abundance_count, sum(abundance) as abundance_sum
        from samples
        join tbl_analysis_entities using (physical_sample_id)
        join tbl_abundances using (analysis_entity_id)
        join taxon_ecocodes using (taxon_id)
        group by samples.physical_sample_id, taxon_ecocodes.ecocode_name

    ) select x.physical_sample_id,
             x.ecocode_name::character varying(150),
             coalesce(sample_ecocode_abundances.abundance_count, 0)::int,
             coalesce(sample_ecocode_abundances.abundance_sum, 0)::int
      from (
          select samples.physical_sample_id, ecocodes.ecocode_name
          from samples
          cross join ecocodes
      ) as x
      left join sample_ecocode_abundances using (physical_sample_id, ecocode_name);
end $BODY$;

ALTER FUNCTION humlab_utility.fn_sample_ecocode_abundances(integer, integer, integer)
    OWNER TO postgres;
```

```sql
-- FUNCTION: humlab_utility.fn_ecocode_crosstab_2_7(integer, text)

-- DROP FUNCTION humlab_utility.fn_ecocode_crosstab_2_7(integer, text);

CREATE OR REPLACE FUNCTION humlab_utility.fn_ecocode_crosstab_2_7(
	p_master_set_id integer,
	p_sum_or_count text)
    RETURNS TABLE(agg_type text, physical_sample_id integer, Aquatics integer, "Indicators: Standing water" integer, "Indicators: Running water" integer, "Pasture/Dung" integer, Meadowland integer, "Wood and trees" integer, "Indicators: Deciduous" integer, "Indicators: Coniferous" integer, "Wetlands/marshes" integer, "Open wet habitats" integer, "Disturbed/arable" integer, "Sandy/dry disturbed/arable" integer, "Dung/foul habitats" integer, Carrion integer, "Indicators: Dung" integer, "Mould beetles" integer, "General synanthropic" integer, "Stored grain pest" integer, "Dry dead wood" integer, "Heathland & moorland" integer, Halotolerant integer, Ectoparasite integer) 
    LANGUAGE 'plpgsql'

    COST 100
    VOLATILE 
    ROWS 1000
AS $BODY$
declare
  v_sql text;
  v_abundance_index int;
begin
    v_abundance_index = case when p_sum_or_count = 'count' then 1 else 2 end;
    return query
        select p_sum_or_count::text as agg_type, cx.physical_sample_id, cx."Aquatics" , cx."Indicators: Standing water" , cx."Indicators: Running water" , cx."Pasture/Dung" , cx."Meadowland" , cx."Wood and trees" , cx."Indicators: Deciduous" , cx."Indicators: Coniferous" , cx."Wetlands/marshes" , cx."Open wet habitats" , cx."Disturbed/arable" , cx."Sandy/dry disturbed/arable" , cx."Dung/foul habitats" , cx."Carrion", cx."Indicators: Dung", cx."Mould beetles", cx."General synanthropic", cx."Stored grain pest", cx."Dry dead wood", cx."Heathland & moorland", cx."Halotolerant", cx."Ectoparasite"
        from crosstab(format('
			select physical_sample_id, ecocode_name::text, (array[abundance_count, abundance_sum])[%s]::int as abundance
        	from humlab_utility.fn_sample_ecocode_abundances(2, 7, %s)', v_abundance_index, p_master_set_id), 
		'values (''Aquatics''::text), (''Indicators: Standing water''::text), (''Indicators: Running water''::text), (''Pasture/Dung''::text), (''Meadowland''::text), (''Wood and trees''::text), 
		(''Indicators: Deciduous''::text), (''Indicators: Coniferous''::text), (''Wetlands/marshes''::text), (''Open wet habitats''::text), (''Disturbed/arable''::text), (''Sandy/dry disturbed/arable''::text), 
		(''Dung/foul habitats''::text), (''Carrion''::text), (''Indicators: Dung''::text), (''Mould beetles''::text), (''General synanthropic''::text), (''Stored grain pest''::text), (''Dry dead wood''::text), 
		(''Heathland & moorland''::text), (''Halotolerant''::text), (''Ectoparasite''::text)') as cx (physical_sample_id int, "Aquatics" int, "Indicators: Standing water" int, "Indicators: Running water" int, 
		"Pasture/Dung" int, "Meadowland" int, "Wood and trees" int, "Indicators: Deciduous" int, "Indicators: Coniferous" int, "Wetlands/marshes" int, "Open wet habitats" int, "Disturbed/arable" int, 
		"Sandy/dry disturbed/arable" int, "Dung/foul habitats" int, "Carrion" int, "Indicators: Dung" int, "Mould beetles" int, "General synanthropic" int, "Stored grain pest" int, "Dry dead wood" int,
		"Heathland & moorland" int, "Halotolerant" int, "Ectoparasite" int)
    ;
end;
$BODY$;

ALTER FUNCTION humlab_utility.fn_ecocode_crosstab_2_7(integer, text)
    OWNER TO postgres;
```

```sql
-- View: humlab_utility.ecocode_dating

-- DROP VIEW humlab_utility.ecocode_dating;

CREATE OR REPLACE VIEW humlab_utility.ecocode_dating AS
 SELECT a.physical_sample_id,
    a.agg_type,
    a.Aquatics,
    a."Indicators: Standing water",
    a."Indicators: Running water",
    a."Pasture/Dung",
    a.Meadowland,
    a."Wood and trees",
    a."Indicators: Deciduous",
    a."Indicators: Coniferous",
    a."Wetlands/marshes",
    a."Open wet habitats",
    a."Disturbed/arable",
    a."Sandy/dry disturbed/arable",
    a."Dung/foul habitats",
    a.Carrion,
    a."Indicators: Dung",
    a."Mould beetles",
    a."General synanthropic",
    a."Stored grain pest",
    a."Dry dead wood",
    a."Heathland & moorland",
    a.Halotolerant,
    a.Ectoparasite,
    d.location_name,
    d.site_id,
    d.site_name,
    d.latitude_dd,
    d.longitude_dd,
    d.dating_type,
    d.age_older,
    d.age_younger,
    d.age_name,
    d.age_abbreviation,
    ps.sample_group_id,
    ps.alt_ref_type_id,
    ps.sample_type_id,
    ps.sample_name,
    ps.date_updated,
    ps.date_sampled
   FROM humlab_utility.fn_ecocode_crosstab_2_7(1, 'count'::text) a(agg_type, physical_sample_id, Aquatics, "Indicators: Standing water", "Indicators: Running water", "Pasture/Dung", Meadowland, "Wood and trees", "Indicators: Deciduous", "Indicators: Coniferous", "Wetlands/marshes", "Open wet habitats", "Disturbed/arable", "Sandy/dry disturbed/arable", "Dung/foul habitats", Carrion, "Indicators: Dung", "Mould beetles", "General synanthropic", "Stored grain pest", "Dry dead wood", "Heathland & moorland", Halotolerant, Ectoparasite)
     JOIN humlab_utility.physical_sample_dating d USING (physical_sample_id)
     JOIN tbl_physical_samples ps USING (physical_sample_id);

ALTER TABLE humlab_utility.ecocode_dating
    OWNER TO postgres;
```

**Comment by Loer0022** [comment]
NOTE: in the querry code the keys should be,

fn_ecocode_crosstab**_2_2** --- the code used here accidentally applied old keys which would simply have given an error output. The 2_2 code will export BugsCEP data.

**Comment by roger-mahler** [comment]
Unfortunately the GeoJSON export turned out to be only half-way implemented. 

Closing this issue in favor of https://github.com/humlab-sead/sead_change_control/issues/64.
