### ISSUE TITLE
Case mistake in data types for Calendar Dates causes import error

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_bugs_import#23]
Error: Datatype Uncalibrated dates not found

Possible cause: tbl_data_types.data_type_name = "calibrated dates" but should be "Calibrated dates"

Solution: Correct  tbl_data_types.data_type_name = "calibrated dates" to "Calibrated dates"

Notes: HOWEVER, error maybe incorrect -needs testing

**Comment by roger-mahler** [comment]
Resolved by [20190513_DML_DATA_TYPE_ADD_TYPES_CALENDER_DATES](https://github.com/humlab-sead/sead_change_control/commit/9f9c804ec08e99d9e37db5f23e249dc73e7b247d#diff-7d9b26e2af687729ff1eee62a7717d93082c4e3c73ef51dae8e9853a67f3a7ca)
