### ISSUE TITLE
SqlException: Value too long for type character varying(25)

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_bugs_import#4]
Import fails with exception "ERROR: value too long for type character varying(25)" when values are inserted into `tbl_taxa_measured_attributes`, column `attribute_type`.

Sample values that exceeeds 25 characters:

- Length larva final (10th) instar
- Length (brachypterous females)
- Length female brachypterous
- Length female macropterous
- Length, head-end of elytra

**Comment by visead** [comment]
Suggest change column attribute_type to varchar(255) in SEAD

**Comment by roger-mahler** [comment]
Solved by increasing size of `tbl_taxa_measured_attributes`, `column attribute_type` to varchar(255).

Added as change request: CS_TAXA_20190503_ATTRIBUTE_TYPE_LENGTH
